### ISSUE TITLE
SyntaxError: Expected atom at position XX

### ISSUE THREAD

**Issue by jsjzgy** [jviereck/regjsparser#107]
When running 262, a use case involving regular expressions will get a syntax error, but the use case design will not get the error
as：
```
match = /[\c_]/.exec('\x1e\x1f\x20');
assert.sameValue(match[0], '\x1f', '\\c_ within CharacterClass');
```

There will be the following syntax errors：
```
SyntaxError: classEscape at position 2
[\c_]
^
```

```
annexB\language\literals\regexp\class-escape.js
annexB\language\literals\regexp\quantifiable-assertion-followed-by.js
annexB\language\literals\regexp\quantifiable-assertion-not-followed-by.js
```
Can you help me troubleshoot @pygy @mathiasbynens @adrianheine @jviereck @kpdecker

**Comment by jviereck** [comment]
Hi, is there a problem with regjsparser or do you ask us to help you debug your regexp?

**Comment by jsjzgy** [comment]
You can fix this problem in regjsparser

**Comment by jviereck** [comment]
Thanks for the clarification. I take a look.

**Comment by jviereck** [comment]
For reference, this is the 262 testsuite file with the problematic case: https://github.com/tc39/test262/blob/main/test/annexB/language/literals/regexp/class-escape.js

**Comment by jviereck** [comment]
A fix was merged into the main branch. I've created a new release version 0.6.7 and published it to npm.

@jsjzgy thanks so much for reporting this. Please let me know in case you find any other issue.
