### ISSUE TITLE
Parsing null char literal \0 reports incorrect range

### ISSUE THREAD

**Issue by robmcl4** [jviereck/regjsparser#111]
version: 0.6.8

The null character literal `\0` reports its range start incorrectly.

```javascript
const parse = require('regjsparser').parse;
console.log(parse('\\0').range);
```

Expectation:

prints `[0, 2]`

What I got:

prints `[-1, 2]`

**Comment by jviereck** [comment]
Should be fixed on the main branch. I also release v0.6.9 to npm.

Thanks for reporting this issue. Please let me know in case you find anything else.
