### ISSUE TITLE
bug: optional forward lookahead

### ISSUE THREAD

**Issue by domdomegg** [jviereck/regjsparser#130]
In JavaScript, the following regex is valid:

```js
/(?=a)?/
```

However, it is rejected by regjsparser (`SyntaxError: Expected atom at position 5`).

I think an optional forward lookahead is a little pointless, but it seems to be used. For example, this appears in the wild in `ua-parser-js`: https://github.com/faisalman/ua-parser-js/blob/3c3c03ceeba9920437533dcf1d72276acac091a3/src/ua-parser.js#L464

**Comment by jviereck** [comment]
Thank you for reporting this issue. I will take a look over the weekend.

**Comment by jviereck** [comment]
Created CR #131.

**Comment by jviereck** [comment]
Fixed and release 0.10.0 published to npm.
