### ISSUE TITLE
Support `\p{…}` and `\P{…}`

### ISSUE THREAD

**Issue by mathiasbynens** [jviereck/regjsparser#77]
While working on [a spec proposal for `\p{…}` and `\P{…}`](https://github.com/mathiasbynens/es-unicode-regexp-proposal/issues/2) I’d like to start prototyping an implementation in [regexpu](https://github.com/mathiasbynens/regexpu).

For now I’d just want regjsparser to parse `\p{foo}` and `\P{bar}` in `u` regexps and expose the `foo` and `bar` values as properties in the AST. Perhaps something like this:

``` js
> regjsparser.parse('\\p{foo}', 'u')
{
  type: 'unicodePropertyEscape',
  negative: false,
  value: 'foo',
  range: [ 0, 7 ],
  raw: '\\p{foo}'
}

> regjsparser.parse('\\P{foo}', 'u')
{
  type: 'unicodePropertyEscape',
  negative: true,
  value: 'foo',
  range: [ 0, 7 ],
  raw: '\\p{foo}'
}
```

Any thoughts/strong preferences on what the AST should look like?

**Comment by jviereck** [comment]
> Any thoughts/strong preferences on what the AST should look like?

LGTM.

**Comment by mathiasbynens** [comment]
Closing since #78 has been merged.
